"""Official Hyafilia USA product catalog used for result-page recommendations."""

PRODUCTS = {
    "cleanser": {
        "key": "cleanser",
        "step": "클렌저",
        "name": "Laperi Perfect Cleansing Gel (200ml)",
        "brand": "LAPERI",
        "price": "$56.00",
        "url": "https://www.hyafiliausa.com/product/laperi-perfect-cleansing-gel-200ml/",
        "image_url": "https://www.hyafiliausa.com/wp-content/uploads/2025/07/Laperi-Cleansing-gel-200ml-fist-page-510x539.png",
        "summary": "자극이 적은 약산성 젤 클렌저",
        "why": "Hyafilia USA는 이 제품을 자연 유래 계면활성제를 사용한 순한 클렌저로 소개합니다.",
        "when": "아침 / 저녁",
    },
    "soothing_toner": {
        "key": "soothing_toner",
        "step": "토너",
        "name": "Dr. Sante Azulene Soother Toner (200ml / 500ml)",
        "brand": "Dr.SANTE",
        "price": "$39.90 - $59.90",
        "url": "https://www.hyafiliausa.com/product/dr-sante-azulene-soother-toner-200ml-500ml/",
        "image_url": "https://www.hyafiliausa.com/wp-content/uploads/2025/10/Dr.Sante-Product-Listing-1-510x510.png",
        "summary": "붉은기 완화와 진정에 초점을 둔 토너",
        "why": "공식 페이지에서 redness relief solution으로 소개되는 진정 토너입니다.",
        "when": "아침 / 저녁",
    },
    "moisture_ampoule": {
        "key": "moisture_ampoule",
        "step": "앰플",
        "name": "Laperi Moisture Fairy Ampoule (30ml)",
        "brand": "LAPERI",
        "price": "$106.50",
        "url": "https://www.hyafiliausa.com/product/laperi-moisture-fairy-ampoule-30ml/",
        "image_url": "https://www.hyafiliausa.com/wp-content/uploads/2025/07/Laperi-Moisture-Fairy-Ampoule-30ml.png",
        "summary": "깊은 보습과 진정을 위한 고농축 앰플",
        "why": "공식 페이지에서 deep hydration과 sensitive skin soothing에 적합한 앰플로 안내합니다.",
        "when": "아침 / 저녁",
    },
    "soothing_cream": {
        "key": "soothing_cream",
        "step": "크림",
        "name": "Dr. Sante Azulene Soother Cream (50ml)",
        "brand": "Dr.SANTE",
        "price": "$38.00",
        "url": "https://www.hyafiliausa.com/product/dr-sante-azulene-soother-cream-50ml/",
        "image_url": "https://www.hyafiliausa.com/wp-content/uploads/2026/01/%EB%8B%A5%ED%84%B0%EC%83%81%EB%96%BC-13%EC%A2%85-%EB%B3%B4%EC%A0%95%EB%B3%B8_-9-510x734.jpg",
        "summary": "민감하고 건조한 피부를 위한 보습 크림",
        "why": "공식 페이지 기준 sensitive skin과 dry skin에 맞춘 moisturizing cream입니다.",
        "when": "저녁 중심 / 건조할 때 아침 추가",
    },
    "blemish_cream": {
        "key": "blemish_cream",
        "step": "트러블 케어",
        "name": "Laperi Blemish Control Gel Cream (50ml)",
        "brand": "LAPERI",
        "price": "$96.60",
        "url": "https://www.hyafiliausa.com/product/laperi-blemish-control-gel-cream-50ml/",
        "image_url": "https://www.hyafiliausa.com/wp-content/uploads/2025/09/Laperi-Blemish-Control-Gel-Cream-_1-510x510.png",
        "summary": "트러블 피부 밸런스를 위한 젤 크림",
        "why": "공식 페이지에서 trouble care를 돕는 라인으로 소개되는 제품입니다.",
        "when": "저녁 중심 / 필요 시 아침 소량",
    },
    "retinol": {
        "key": "retinol",
        "step": "집중 케어",
        "name": "Beldora +Prime Retinol Activator 0.3 35ml",
        "brand": "BELDORA",
        "price": "$59.99",
        "url": "https://www.hyafiliausa.com/product/beldora-prime-retinol-activator_0-3/",
        "image_url": "https://www.hyafiliausa.com/wp-content/uploads/2024/09/0.3-510x602.png",
        "summary": "주름과 탄력 저하를 위한 야간 레티놀 케어",
        "why": "공식 페이지에서 anti-wrinkle night cream으로 안내되며 night use를 권장합니다.",
        "when": "저녁 전용",
    },
    "sunscreen": {
        "key": "sunscreen",
        "step": "선케어",
        "name": "Curenex Daily Sheer Sunscreen SPF50+ PA++++ 50ml",
        "brand": "CURENEX",
        "price": "$49.99",
        "url": "https://www.hyafiliausa.com/product/curenex-daily-sheer-sunscreen-spf50-pa-50ml/",
        "image_url": "https://www.hyafiliausa.com/wp-content/uploads/2025/01/admin-ajax-510x510.jpeg",
        "summary": "민감 피부까지 고려한 고지수 자외선 차단제",
        "why": "공식 페이지에서 sensitive skin에 적합하고 UVA/UVB protection을 제공한다고 안내합니다.",
        "when": "아침 / 외출 전",
    },
}
